# Generated by Django 2.2.1 on 2019-07-21 12:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engineering_University',
            fields=[
                ('uId', models.IntegerField(primary_key=True, serialize=False)),
                ('uName', models.CharField(max_length=500)),
                ('requireGpa', models.DecimalField(decimal_places=2, max_digits=2)),
                ('background', models.CharField(max_length=50)),
                ('passingyear', models.IntegerField(verbose_name=models.IntegerField(default=2019))),
                ('English', models.DecimalField(decimal_places=2, max_digits=2)),
                ('pyhsics', models.DecimalField(decimal_places=2, max_digits=2)),
                ('chemistry', models.DecimalField(decimal_places=2, max_digits=2)),
                ('math', models.DecimalField(decimal_places=2, max_digits=2)),
                ('location', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=250)),
                ('examdate', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='General_University',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('uName', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Medical_College',
            fields=[
                ('uId', models.IntegerField(primary_key=True, serialize=False)),
                ('uName', models.CharField(max_length=500)),
                ('requireGpa', models.DecimalField(decimal_places=2, max_digits=2)),
                ('passingyear', models.IntegerField(verbose_name=models.IntegerField(default=2019))),
                ('location', models.CharField(max_length=250)),
                ('website', models.CharField(max_length=250)),
                ('biology', models.DecimalField(decimal_places=2, max_digits=2)),
                ('english', models.DecimalField(decimal_places=2, max_digits=2)),
                ('examdate', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Science_And_Technology',
            fields=[
                ('universityid', models.IntegerField(primary_key=True, serialize=False)),
                ('uName', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Science_And_Technology_requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=1)),
                ('requireGpa', models.DecimalField(decimal_places=2, max_digits=2)),
                ('background', models.CharField(max_length=50)),
                ('passingyear', models.IntegerField(verbose_name=models.IntegerField(default=2019))),
                ('examdate', models.DateField(default=datetime.datetime.now)),
                ('uId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainWeb.Science_And_Technology')),
            ],
        ),
        migrations.CreateModel(
            name='General_University_requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requireGpa', models.DecimalField(decimal_places=2, max_digits=2)),
                ('unit', models.CharField(max_length=1)),
                ('background', models.CharField(max_length=50)),
                ('passingyear', models.IntegerField(verbose_name=models.IntegerField(default=2019))),
                ('examdate', models.DateField(default=datetime.datetime.now)),
                ('universityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainWeb.General_University')),
            ],
        ),
    ]
