# Generated by Django 2.2.1 on 2019-07-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWeb', '0002_auto_20190721_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineering_university',
            name='English',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='engineering_university',
            name='chemistry',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='engineering_university',
            name='math',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='engineering_university',
            name='pyhsics',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='engineering_university',
            name='requireGpa',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='general_university_requirement',
            name='requireGpa',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='medical_college',
            name='biology',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='medical_college',
            name='english',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='medical_college',
            name='requireGpa',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='science_and_technology_requirement',
            name='requireGpa',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
